# Generated by Django 5.2.8 on 2025-12-30 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0002_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=150)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('children', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_policy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('willing_to_switch', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('aadhar', models.CharField(max_length=12, unique=True)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insuranceapp.agent')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insuranceapp.campaign')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
