from django.urls import path
from . import views

urlpatterns=[
    path('',views.home,name="home"),
    path('loginpage',views.loginpage,name="loginpage"),
    path('login1',views.login1,name="login1"),
    path('adminhome',views.adminhome,name="adminhome"),
    path('add_agent',views.add_agent,name="add_agent"),
    path('add_agentdb',views.add_agentdb,name="add_agentdb"),
    path('view_agent',views.view_agent,name="view_agent"),
    path('edit_agent/<int:pk>',views.edit_agent,name="edit_agent"),
    path('edit_agentdb/<int:pk>',views.edit_agentdb,name="edit_agentdb"),
    path('a_delete/<int:pk>',views.a_delete,name="a_delete"),
    path('add_campaign',views.add_campaign,name="add_campaign"),
    path('add_campaigndb',views.add_campaigndb,name="add_campaigndb"),
    path('campaigns/', views.view_campaigns, name='view_campaigns'),
    path('campaign/delete/<int:pk>/', views.delete_campaign, name='delete_campaign'),
    path('campaign/edit/<int:pk>/', views.edit_campaign, name='edit_campaign'), 
    path('logout/',views.logout,name="logout"),
    path('agenthome', views.agenthome, name='agenthome'),
    path('assigned_campaigns', views.assigned_campaigns, name='assigned_campaigns'),
    path('add_client', views.add_client, name='add_client'),
    path('add_clientdb', views.add_clientdb, name='add_clientdb'),
    path('view_clients', views.view_clients, name='view_clients'),
    path('client_detail/<int:pk>/', views.client_detail, name='client_detail'),
    path('edit_client/<int:pk>/', views.edit_client, name='edit_client'),
    path('edit_clientdb/<int:pk>/', views.edit_clientdb, name='edit_clientdb'),
    path('delete_client/<int:pk>/', views.delete_client, name='delete_client'),
    path('edit_profile',views.edit_profile,name="edit_profile"),
    path('edit_profiledb',views.edit_profiledb,name="edit_profiledb"),
    path('view_profile', views.view_profile, name='view_profile'),
    path('r_password',views.r_password,name="r_password"),
    path('reset',views.reset,name="reset"),
    path('admin_view_clients', views.admin_view_clients, name='admin_view_clients'),
    path('admin_client_detail/<int:pk>', views.admin_client_detail, name='admin_client_detail'),
    path('contactdb/', views.contactdb, name='contactdb'),
    path('ajax/validate/', views.ajax_validate_user_fields, name='ajax_validate'),
    path('ajax/validate-reset-password/', views.ajax_validate_reset_password,name="validate-reset-password"),
    path('ajax/login-validate/', views.ajax_login_validate, name='ajax_login_validate'),
    
]